### PR TITLE
chore: generate unit test code

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by xxuejie** [comment]
Why not update `tests/src/tests.rs` file directly?

**Review by XuJiandong — APPROVED** [review]

**Comment by quake** [comment]
> Why not update `tests/src/tests.rs` file directly?

cargo generate cannot work on the final destination folder, we have to use a script to modify this file.

**Comment by xxuejie** [comment]
> > Why not update `tests/src/tests.rs` file directly?
> 
> cargo generate cannot work on the final destination folder, we have to use a script to modify this file.

I mean in the pull request, we can update `tests/src/tests.rs` file directly to contain the unit test. There is no need to generate a template using a previous ` tests/src/tests.rs` file, then update it later with another file.

**Comment by quake** [comment]
> I mean in the pull request, we can update `tests/src/tests.rs` file directly to contain the unit test. There is no need to generate a template using a previous ` tests/src/tests.rs` file, then update it later with another file.


I want to generate unit test per contract automatically

```rust
fn test_{{crate_name}}() {
    // deploy contract
    let mut context = Context::default();
    let contract_bin: Bytes = Loader::default().load_binary("{{project-name}}");
```

**Comment by xxuejie** [comment]
Ah I see what this means here, but to me that brings more questions:

* Shall we put this test in each individual contract crate, or shall we put this in the `tests` folder for the global workspace? Feels like this is a question we haven't discussed.
* The code right now only deals with `contract` template, but we also have templates for other contracts(`c-wrapper-crate`, `atomics-contract`, etc.), those additional templates have not been taken care of. So maybe a better solution here, is to put the unit test snippet at the workspace level? For example, we can have a `snippets` folder in the root of workspace, and we can simply create the tests needed from files in this `snippets` folder.

**Comment by quake** [comment]
> Shall we put this test in each individual contract crate, or shall we put this in the tests folder for the global workspace? Feels like this is a question we haven't discussed.

I prefer put test in individual contract folder, however, capsule and script-templates put it in the global workspace, I think it's better to follow the previous convention.

> The code right now only deals with contract template, but we also have templates for other contracts(c-wrapper-crate, atomics-contract, etc.)

I haven't looked the detail of these template tests, are they the same as regular contract tests? If they are, I can add them as your suggestion.

**Comment by xxuejie** [comment]
> I haven't looked the detail of these template tests, are they the same as regular contract tests? If they are, I can add them as your suggestion.

They are the same contract template you can add to the workspace, with varying options.

**Comment by xxuejie** [comment]
> I prefer put test in individual contract folder, however, capsule and script-templates put it in the global workspace, I think it's better to follow the previous convention.

Personally, I don't think following existing conventions here is that important, we are already introducing new tool with different commands.

**Comment by quake** [comment]
>  For example, we can have a snippets folder in the root of workspace, and we can simply create the tests needed from files in this snippets folder.

I tried to change it this way, but I found that cargo generate can't read files from the current workspace directory unless we change it with sed, but that makes the shell script complicated, so I went with the easy way: put a `test-generate.rs` file in each template directory. Please help to review again, thanks.

**Comment by xxuejie** [comment]
I understand the cause here, and I'm fine with the solution, but at least can we move all those `test-generate.rs` files at the root of each template to a designated folder? For example, we can have:

* `contract/_to_remove/test-generate.rs`
* `stack-reorder-contract/_to_remove/test-generate.rs`
* `atomics-contract/_to_remove/test-generate.rs`

This way at least we know the files in `_to_remove` are only there for template creation purposes, and will be expected to be removed later. We can also reuse the same folder for similar purposes in the future.

**Comment by xxuejie** [comment]
And one more thing: it possible to generate a single contract as a repo, instead of using a workspace, do you think it makes sense to add a default unit test for the single standalone contract here: https://github.com/cryptape/ckb-script-templates/tree/main/standalone-contract?

**Comment by quake** [comment]
> I understand the cause here, and I'm fine with the solution, but at least can we move all those `test-generate.rs` files at the root of each template to a designated folder? For example, we can have:
> 
> * `contract/_to_remove/test-generate.rs`
> * `stack-reorder-contract/_to_remove/test-generate.rs`
> * `atomics-contract/_to_remove/test-generate.rs`
> 
> This way at least we know the files in `_to_remove` are only there for template creation purposes, and will be expected to be removed later. We can also reuse the same folder for similar purposes in the future.

Added a folder `.cargo_generate`

> And one more thing: it possible to generate a single contract as a repo, instead of using a workspace, do you think it makes sense to add a default unit test for the single standalone contract here: https://github.com/cryptape/ckb-script-templates/tree/main/standalone-contract?

Resolved

Please help to review again, thanks.

**Review by xxuejie — APPROVED** [review]

**Pull request merged**
